config/routes.rb
Rails.application.routes.draw do
  
  get 'services/index'
  get 'project/index'
  get 'about/index'
  get 'home/index'
  get 'newcustomerok/index'

  devise_for :users
  resources :customers
  
  get 'cities/:state', to: 'application#cities'

  root 'home#index'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  validates :first_name, {presence: true}
  validates :last_name, {presence: true}
  validates :birthday, {presence: true}
  validate :birthday_validate  
  validates :gender, {presence: true}
  validates :mobile_phone, {presence: true}
  validates :email, {presence: true}
  validates :state, {presence: true}  
  validates :city, {presence: true}
  validates :address, {presence: true}
  validates :zip_code, {presence: true, :length => {minimum: 5} }

  private

  def birthday_validate
    if birthday.year > (Date.today.year - 15)
      errors.add( "The birthday date must be greater than ",(Date.today.year - 15).to_s + (birthday.strftime "-%m-%d").to_s )
    end    
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
#  devise :database_authenticatable, :registerable,
#         :recoverable, :rememberable, :trackable, :validatable
# :registerable  hace que no se pueda hacer new_user_registration_path
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def cities
    render json: CS.cities(params[:state], :us)
  end
  
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:new, :create, :show]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
    respond_to do |format|
      format.html
      format.xlsx {
        response.headers['Content-Disposition'] = 'attachment; filename="customers.xlsx"'
      }
    end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    if not user_signed_in?
      redirect_to newcustomerok_index_url
    end
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:first_name, :last_name, :birthday, :gender, :mobile_phone, :other_phone, :email, :address, :city, :state, :zip_code, :comments)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/newcustomerok_controller.rb
class NewcustomerokController < ApplicationController
  def index
  end
end

app/controllers/project_controller.rb
class ProjectController < ApplicationController
  def index
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/customers/_form.html.erb
<%if not user_signed_in? %>
  <section class="well-sm wow fadeIn  bg1" data-wow-duration='3s'>
    <div class="container">
      <h3 class="txt-pr">
        CONTACT US <br/>
        <small>
          Fill out the form below to learn more!
        </small>
      </h3>
    </div>
  </section>
<%end%>

<%= form_for @customer, html: {name: "contact_form", id: "contact_form", class: "well1 form-horizontal"} do |f| %>

  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <!-- Form Name -->
    <div class="form-group">
      <label class="col-md-4 control-label">First Name</label>
      <div class="col-md-4 inputGroupContainer">
        <div class="input-group">
          <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
          <%= f.text_field :first_name, class: "form-control", placeholder: "First Name" %>
        </div>
      </div>
    </div><!-- Text input-->
    <div class="form-group">
      <label class="col-md-4 control-label">Last Name</label>
      <div class="col-md-4 inputGroupContainer">
        <div class="input-group">
          <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
          <%= f.text_field :last_name, class: "form-control", placeholder: "Last Name" %>
        </div>
      </div>
    </div><!-- Text input-->
    <div class="form-group">
      <label class="col-md-4 control-label">E-Mail</label>
      <div class="col-md-4 inputGroupContainer">
        <div class="input-group">
          <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
          <%= f.email_field :email, class: "form-control", placeholder: "email@domain.com" %>
        </div>
      </div>
    </div><!-- Text input-->

    <div class="form-group">
      <label class="col-md-4 control-label">Mobile phone #</label>
      <div class="col-md-4 inputGroupContainer">
        <div class="input-group">
          <span class="input-group-addon"><i class="glyphicon glyphicon-earphone"></i></span>
          <%= f.text_field :mobile_phone, class: "form-control", placeholder: "(845)555-1212" %>
        </div>
      </div>
    </div><!-- Text input-->

    <div class="form-group">
      <label class="col-md-4 control-label">Other Phone #</label>
      <div class="col-md-4 inputGroupContainer">
        <div class="input-group">
          <span class="input-group-addon"><i class="glyphicon glyphicon-earphone"></i></span>
          <%= f.text_field :other_phone, class: "form-control", placeholder: "office, beeper, etc." %>
        </div>
      </div>
    </div><!-- Text input-->

    <div class="form-group">
      <label class="col-md-4 control-label">State</label>
      <div class="col-md-4 selectContainer">
        <div class="input-group">
          <span class="input-group-addon"><i class="glyphicon glyphicon-list"></i></span>
          <%= f.select(:state, {}, {}, :class => 'form-control') do %>
            <%= content_tag(:option, "Select Your State" , value: " " ) %>
            <% CS.states(:us).each do |key, value| %>
              <% if key.to_s == @customer.state %>
                <%= content_tag(:option, value , value: key , selected: true ) %>
              <% else %>
                <%= content_tag(:option, value , value: key ) %>
              <% end %>
            <% end %>
          <%end%>
        </div>
      </div>
    </div><!-- Text input-->

    <div class="form-group">
      <label class="col-md-4 control-label">City</label>
      <div class="col-md-4 inputGroupContainer">
        <div class="input-group">
          <span class="input-group-addon"><i class="glyphicon glyphicon-list"></i></span>
          <% if @customer.state.blank? %>
            <%= f.select(:city, [["Select Your City",""]], {}, :class => 'form-control') %>
          <%else%>
            <%= f.select(:city, {}, {}, :class => 'form-control') do %>
              <%= content_tag(:option, "Select Your City" , value: " " ) %>
              <% CS.cities(@customer.state, :us).each do |key, value| %>
                <% if key.to_s == @customer.city %>
                  <%= content_tag(:option, key.to_s, value: key.to_s , selected: true ) %>
                <% else %>
                  <%= content_tag(:option, key.to_s , value: key.to_s ) %>
                <% end %>
              <% end %>
            <% end %>
          <%end%>
        </div>
      </div>
    </div><!-- Select Basic -->

    <div class="form-group">
      <label class="col-md-4 control-label">Address</label>
      <div class="col-md-4 inputGroupContainer">
        <div class="input-group">
          <span class="input-group-addon"><i class="glyphicon glyphicon-home"></i></span>
          <%= f.text_field :address, class: "form-control", placeholder: "Address" %>
        </div>
      </div>
    </div><!-- Text input-->

    <div class="form-group">
      <label class="col-md-4 control-label">Zip Code</label>
      <div class="col-md-4 inputGroupContainer">
        <div class="input-group">
          <span class="input-group-addon"><i class="glyphicon glyphicon-home"></i></span>
          <%= f.text_field :zip_code, class: "form-control", placeholder: "99999" %>
        </div>
      </div>
    </div><!-- Text input-->

    <div class="form-group">
      <label class="col-md-4 control-label">Gender</label>
      <div class="col-md-4">
        <% v_log_check_male   = false
          v_log_check_female = false
          v_log_check_other  = false
          if @customer.gender == "Male"
            v_log_check_male = true
          else
            if @customer.gender == "Female"
              v_log_check_female = true
            else
              if @customer.gender == "Other"
                v_log_check_other = true
              else
                v_log_check_male = true
              end
            end
          end%>
        <div class="form-control">
          <label class="radio_label">
            <%= radio_button_tag("customer[gender]", "Male", checked = v_log_check_male) %> Male
          </label>
          <label class="radio_label">
            <%= radio_button_tag("customer[gender]", "Female", checked = v_log_check_female) %> Female
          </label>
          <label class="radio_label">
            <%= radio_button_tag("customer[gender]", "Other", checked = v_log_check_other) %> Other
          </label>
        </div>
      </div>
    </div><!-- Text area -->

    <%#= f.hidden_field :birthday, value: "1982-09-01" %>

    <div class="form-group">
      <label class="col-md-4 control-label">Birthday</label>
      <div class="col-md-4 inputGroupContainer">
        <div class="input-group">
          <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
          <%= f.date_select :birthday,{start_year: Date.today.year - 120, end_year: Date.today.year - 17 }, class: "form-control" %>
        </div>
      </div>
    </div><!-- Success message -->


    <div class="form-group">
      <label class="col-md-4 control-label">Comments</label>
      <div class="col-md-4 inputGroupContainer">
        <div class="input-group">
          <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
          <%= f.text_area :comments, class: "form-control", placeholder: "Type your message here...", rows: "4" %>
        </div>
      </div>
    </div><!-- Success message -->
    <div class="alert alert-success" id="success_message" role="alert">
      Success <i class="glyphicon glyphicon-thumbs-up"></i> Thanks for contacting us, we will get back to you shortly.
    </div><!-- Button -->
    <div class="form-group">
      <label class="col-md-4 control-label"></label>
      <div class="col-md-3">
        <button class="btn btn-warning" type="submit">Send <span class="glyphicon glyphicon-send"></span></button>
      </div>
    </div>
  </fieldset>

<% end %>

<script>
  $("#customer_state").change(function () {
    var input_state = $(this);
    var input_city = $("#customer_city");
    $.getJSON('/cities/' + input_state.val(), function (data) {
      var opt = '<option value="" selected="">Select Your City</option>';
      //console.log(data);
      if(data.length > 0){
        data.forEach(function(i) {
          opt += "<option value=" + i + ">" + i + '</option>';
        });
      }
      input_city.html(opt);
    });
  });
</script>

app/views/customers/edit.html.erb
<%= render 'form' %>
<h4>
  <%= link_to 'Show', @customer %> |
  <%= link_to 'Back', customers_path %>
</h4>

app/views/customers/index.html.erb
<div class="container-fluid">
	<h4>
    <%= link_to 'Download as .xlsx', customers_path(format: :xlsx) %>
  </h4>
	<table id="grid" class="table table-customized table-hover" data-selection="true" data-multi-select="true" data-row-select="true" data-keep-selection="true">
		<thead class="">
		<tr>
			<th data-column-id="id" data-identifier="true" data-type="numeric" data-align="right" data-width="50">ID</th>
			<th data-column-id="firstName"data-align="left" data-header-align="left" data-width="150px">First name</th>
			<th data-column-id="lastName" data-order="asc">Last name</th>
			<th data-column-id="birthday">Birthday</th>
			<th data-column-id="gender" data-width="90px">Gender</th>
			<th data-column-id="mobilePhone" data-sortable="false">Cell phone</th>
			<th data-column-id="otherPhone" data-sortable="false" data-visible="false">Other phone</th>
			<th data-column-id="email" data-sortable="false" data-visible="false">Email</th>
			<th data-column-id="address" data-visible="false">Address</th>
			<th data-column-id="city">City</th>
			<th data-column-id="state">State</th>
			<th data-column-id="zipCode" data-width="100px">Zip code</th>
			<th data-column-id="info" data-formatter="info" data-sortable="false" data-width="35px" data-align="left"></th>
			<th data-column-id="edit" data-formatter="edit" data-sortable="false" data-width="35px"></th>
		</tr>
		</thead>

		<tbody id="myTable">
		<% @customers.order("created_at desc").each do |customer| %>
			<tr>
			<td><%= customer.id %></td>
			<td><%= customer.first_name %></td>
			<td><%= customer.last_name %></td>
			<td><%= customer.birthday %></td>
			<td><%= customer.gender %></td>
			<td><%= customer.mobile_phone %></td>
			<td><%= customer.other_phone %></td>
			<td><%= customer.email %></td>
			<td><%= customer.address %></td>
			<td><%= customer.city %></td>
			<% CS.states(:us).each do |key, value| %>
				<% if key.to_s == customer.state %>
					<%= content_tag(:td, value) %>
					<% break %>
				<%end%>
			<%end%>
			<td><%= customer.zip_code %></td>
			<td>
				<!--<%= button_to [customer] , class: "btn-table btn-sm px-2", method: "get" do %>
					<i class="fa fa-info-circle mt-0"></i>
				<%end%>-->
			</td>
			<td>
				<!--<%= button_to [:edit, customer] , class: "btn-table btn-sm px-2", method: "get" do %>
					<i class="fa fa-pencil mt-0"></i>
				<%end%>-->
			</td>
			</tr>
		<%end%>
		</tbody>
	</table>
</div>

<script>

	$(function() {
		function init() {
			$("#grid").bootgrid( {
				formatters: {
					"info": function(column, row) {
						return " <form class='button_to' method='get' action='/customers/" + row.id + "'><button class='btn-table btn-sm px-2' type='submit'>"
										+ "<i class='fa fa-info-circle mt-0'></i>"
										+ "</button></form>" ;
					},
					"edit": function (column, row) {
						return "<form class='button_to' method='get' action='/customers/" + row.id + "/edit'><button class='btn-table btn-sm px-2' type='submit'>"
										+ "<i class='fa fa-pencil mt-0'></i>"
										+ "</button></form>" ;
					}
				},
				rowCount: [-1, 10, 50, 75]
			});
		}			
		init();
	});

	$.fn.bootgrid.Constructor = Grid;

	;(function ($, window, undefined) {
		/*jshint validthis: true */
		"use strict";

		$.extend($.fn.bootgrid.Constructor.defaults.css, {
			icon: "icon fa",
			iconColumns: "fa-th-list",
			iconDown: "fa-sort-desc",
			iconRefresh: "fa-refresh",
			iconSearch: "fa-search",
			iconUp: "fa-sort-asc"
		});
	})(jQuery, window);

	!function(a,b,c){"use strict";a.extend(a.fn.bootgrid.Constructor.defaults.css,{icon:"icon fa",iconColumns:"fa-th-list",iconDown:"fa-sort-desc",iconRefresh:"fa-refresh",iconSearch:"fa-search",iconUp:"fa-sort-asc"})}(jQuery,window);

	$.extend($.fn.bootgrid.Constructor.defaults.css, {
		icon: "icon fa",
		iconColumns: "fa-th-list",
		iconDown: "fa-sort-desc",
		iconRefresh: "fa-refresh",
		iconSearch: "fa-search",
		iconUp: "fa-sort-asc"
	});	  
</script>

app/views/customers/new.html.erb
<%= render 'form' %>
<% if user_signed_in? %>
  <h4>
    <%= link_to 'Customers', customers_path %>
  </h4>
<%end%>

app/views/customers/show.html.erb
<fieldset class="form-horizontal">
  <div class="form-group-customized form-group">
    <label class="col-md-4 form-customized control-label">First Name</label>
    <div class="col-md-4 inputGroupContainer">
      <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
        <div class="form-customized form-control" readonly>
          <%= @customer.first_name %>
        </div>
      </div>
    </div>
  </div><!-- Text input-->

  <div class="form-group-customized form-group">
    <label class="col-md-4 form-customized control-label">Last Name</label>
    <div class="col-md-4 inputGroupContainer">
      <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
        <div class="form-customized form-control" readonly>
          <%= @customer.last_name %>
        </div>
      </div>
    </div>
  </div><!-- Text input-->

  <div class="form-group-customized form-group">
    <label class="col-md-4 form-customized control-label">Email</label>
    <div class="col-md-4 inputGroupContainer">
      <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
        <div class="form-customized form-control" readonly>
          <%= @customer.email %>
        </div>
      </div>
    </div>
  </div><!-- Text input-->

  <div class="form-group-customized form-group">
    <label class="col-md-4 form-customized control-label">Mobile phone</label>
    <div class="col-md-4 inputGroupContainer">
      <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-earphone"></i></span>
        <div class="form-customized form-control" readonly>
          <%= @customer.mobile_phone %>
        </div>
      </div>
    </div>
  </div><!-- Text input-->

  <div class="form-group-customized form-group">
    <label class="col-md-4 form-customized control-label">Other phone</label>
    <div class="col-md-4 inputGroupContainer">
      <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-earphone"></i></span>
        <div class="form-customized form-control" readonly>
          <%= @customer.other_phone %>
        </div>
      </div>
    </div>
  </div><!-- Text input-->

  <div class="form-group-customized form-group">
    <label class="col-md-4 form-customized control-label">State</label>
    <div class="col-md-4 inputGroupContainer">
      <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-list"></i></span>
        <div class="form-customized form-control" readonly>
          <% CS.states(:us).each do |key, value| %>
            <% if key.to_s == @customer.state %>
              <%= value %>
              <% break %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div><!-- Text input-->

  <div class="form-group-customized form-group">
    <label class="col-md-4 form-customized control-label">City</label>
    <div class="col-md-4 inputGroupContainer">
      <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-list"></i></span>
        <div class="form-customized form-control" readonly>
          <%= @customer.city %>
        </div>
      </div>
    </div>
  </div><!-- Text input-->

  <div class="form-group-customized form-group">
    <label class="col-md-4 form-customized control-label">Address</label>
    <div class="col-md-4 inputGroupContainer">
      <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-home"></i></span>
        <div class="form-customized form-control" readonly>
          <%= @customer.address %>
        </div>
      </div>
    </div>
  </div><!-- Text input-->

  <div class="form-group-customized form-group">
    <label class="col-md-4 form-customized control-label">Zip code</label>
    <div class="col-md-4 inputGroupContainer">
      <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-home"></i></span>
        <div class="form-customized form-control" readonly>
          <%= @customer.zip_code %>
        </div>
      </div>
    </div>
  </div><!-- Text input-->

  <div class="form-group-customized form-group">
    <label class="col-md-4 form-customized control-label">Gender</label>
    <div class="col-md-4">
      <% v_log_check_male   = false
         v_log_check_female = false
         v_log_check_other  = false
        if @customer.gender == "Male"
          v_log_check_male = true
        else
          if @customer.gender == "Female"
            v_log_check_female = true
          else
            if @customer.gender == "Other"
              v_log_check_other = true
            else
              v_log_check_male = true
            end
          end
        end%>
      <div class="form-control" readonly>
        <label class="radio_label">
          <%= radio_button_tag("customer[gender]", "Male", checked = v_log_check_male, disabled: true) %> Male
        </label>
        <label class="radio_label">
          <%= radio_button_tag("customer[gender]", "Female", checked = v_log_check_female, disabled: true) %> Female
        </label>
        <label class="radio_label">
          <%= radio_button_tag("customer[gender]", "Other", checked = v_log_check_other, disabled: true) %> Other
        </label>
      </div>
    </div>
  </div><!-- Text area -->

  <div class="form-group-customized form-group">
    <label class="col-md-4 form-customized control-label">Birthday</label>
    <div class="col-md-4 inputGroupContainer">
      <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
        <div class="form-customized form-control" readonly>
          <%= @customer.birthday %>
        </div>
      </div>
    </div>
  </div><!-- Text input-->

  <div class="form-group-customized form-group">
    <label class="col-md-4 form-customized control-label">Comments</label>
    <div class="col-md-4 inputGroupContainer">
      <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
          <textarea class="form-textarea-customized form-control" rows="4" readonly><%= @customer.comments %></textarea>
      </div>
    </div>
  </div><!-- Text input-->

</fieldset>

<h4>
  <div class="col-md-4">
    <%= link_to 'Edit', edit_customer_path(@customer) %> | 
    <%= link_to 'Back', customers_path %>
  </div>
  <div class="col-md-6">
  </div>
  <div class="col-md-2">
    <%= link_to 'Delete', customer_path(@customer), method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
</h4>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CustomerRegistration</title>
  
  <!-- Add jQuery library -->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>  
  <%= csrf_meta_tags %>
  <link rel="icon" href= <%= image_path("favicon.ico")%> type="image/x-icon">
</head>
<body>

  <div class="page">
  <!--========================================================
                            HEADER
  =========================================================-->
    <header>  
      <div class="container top-sect">
        <div class="navbar-header">
          <h1 class="navbar-brand">
            <a data-type='rd-navbar-brand'  href="./">business<small>company</small></a>
          </h1>
          <a class="search-form_toggle" href="#"></a>
        </div>

        <div class="help-box text-right">
          <p>Need help?</p>
          <a href="callto:#">800-2345-6789</a>
          <small><span>Hours:</span>  6am-4pm PST M-Th; &nbsp;6am-3pm PST Fri</small>
        </div>
			</div>
                  
      <div id="stuck_container" class="stuck_container">
        <div class="container">
          <nav class="navbar navbar-default navbar-static-top pull-left">
            <div class="">  
              <ul class="nav navbar-nav sf-menu" data-type="navbar">
                <li>
                  <%= link_to "HOME", home_index_path %>
                </li>
                <li>
                  <%= link_to "ABOUT", about_index_path %>
                </li>
                <li class="dropdown">
                  <%= link_to services_index_path do %>
                    SERVICES<span class="glyphicon glyphicon-menu-down" aria-hidden="true"></span>
                  <% end %>
                  <ul class="dropdown-menu">
                    <li>
                      <a href="#">Lorem ipsum</a>
                    </li>
                    <li>
                      <a href="#">Dolor sit amet  </a>
                    </li>
                    <li>
                      <a href="#">Conse ctetur </a>
                        <ul class="dropdown-menu">
                          <li>
                            <a href="#">Latest</a>
                          </li>
                          <li>
                            <a href="#">Archive</a>
                          </li>
                        </ul>
                    </li>
                  </ul>
                </li>
                <li>
                  <%= link_to "PROJECTS", project_index_path %>
                </li>                
                <li>
                  <%= link_to "CONTACTS", new_customer_path %>
                </li>
                <% if user_signed_in? %>
                  <li>
                    <%= link_to "CUSTOMERS", customers_path %>
                  </li>
                <% end %>
                <li>
                  <% if user_signed_in? %>                    
                    <%= link_to "LOG OUT", destroy_user_session_path, method: :delete, class: "log-customized" %>
                  <%else%>
                    <%= link_to "LOG IN", new_user_session_path, class: "log-customized" %>
                  <%end%>
                </li>
              </ul>
            </div>
          </nav>
        </div>
      </div>
		</header>

    <div class="row">
      <div class="col-xs-10 col-xs-offset-1">
        <% flash.each do |type, msg| %>
          <% if type == "notice" %>
            <div class="alert alert-success">
          <% elsif type == "alert" %>
            <div class="alert alert-danger">
          <% else %>
            <div class='alert alert-<%= "#{type}" %>'>
          <% end %>
            <a href="#" class="close" data-dismiss="alert">&#215;</a>
            <ul>
              <li>
                <%= msg %>
              </li>
            </ul>
          </div>
        <% end %>
      </div>
    </div>

		<div class="container">

      <%= yield %>
      
		</div>    
	</div>
  
  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <!-- Include all compiled plugins (below), or include individual files as needed-->
  <script type="text/javascript" src="/assets/bootstrap.js"></script>
  <script type="text/javascript" src="/assets/bootstrap.min.js"></script>
  <script type="text/javascript" src="/assets/tm-scripts.js"></script>
  
  <script> 
    $(document).ready(function () {
        RDMobilemenu_autoinit('[data-type="navbar"]');
    });

    function actionFormatter(value, row, index) {
    return [
      '<a class="like" href="javascript:void(0)" title="Like">',
      '<i class="glyphicon glyphicon-heart"></i>',
      '</a>',
      '<a class="edit ml10" href="javascript:void(0)" title="Edit">',
      '<i class="glyphicon glyphicon-edit"></i>',
      '</a>',
      '<a class="remove ml10" href="javascript:void(0)" title="Remove">',
      '<i class="glyphicon glyphicon-remove"></i>',
      '</a>'
    ].join('');
    }

    window.actionEvents = {
    'click .like': function (e, value, row, index) {
      alert('You click like icon, row: ' + JSON.stringify(row));
      console.log(value, row, index);
    },
    'click .edit': function (e, value, row, index) {
      alert('You click edit icon, row: ' + JSON.stringify(row));
      console.log(value, row, index);
    },
    'click .remove': function (e, value, row, index) {
      alert('You click remove icon, row: ' + JSON.stringify(row));
      console.log(value, row, index);
    }
    };
  </script>

</body>
</html>

app/views/newcustomerok/index.html.erb
<section class="well-sm wow fadeIn  bg1" data-wow-duration='3s'>
  <div class="container">
    <h3 class="txt-pr">
      Thank you for your registration! <br/>
      <small>
        Soon we will contact you!
      </small>
    </h3>
  </div>
</section>